/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import java.sql.*;
import classes.get_connection;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Eliminar_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar_Clientes
     */
    public Eliminar_Clientes() {
        initComponents();
        setTitle("Informacion de eliminacion del cliente.");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon imag_1 = new ImageIcon("src/images/wallpaper2.png");

        Icon ic_1 = new ImageIcon(imag_1.getImage().getScaledInstance(jLabel_wallpaper4.getWidth(),
                jLabel_wallpaper4.getHeight(), Image.SCALE_DEFAULT));

        jLabel_wallpaper4.setIcon(ic_1);

        this.repaint();

        try {

            Connection cn_2 = get_connection.connect();
            PreparedStatement pst_2 = cn_2.prepareStatement("select * from clientes where nombre_cliente = '" + Tabla_Eliminar_Clientes.client_delete + "'");

            ResultSet rs_2 = pst_2.executeQuery();

            if (rs_2.next()) {

                jTextField_Name.setText(rs_2.getString("nombre_cliente"));
                jTextField_email.setText(rs_2.getString("email_cliente"));
                jTextField_telefono.setText(rs_2.getString("tel_cliente"));
                jTextField_direccion.setText(rs_2.getString("dir_cliente"));
                jTextField_ultimaMody.setText(rs_2.getString("ultima_modificacion"));

            }

        } catch (SQLException e) {
            System.err.println("SQL ERROR! " + e);
        }

    }
    
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logo_icon2.png"));
        
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_ultimaMody = new javax.swing.JTextField();
        jTextField_direccion = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_wallpaper4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_ultimaMody.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_ultimaMody.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_ultimaMody.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField_ultimaMody, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 235, 210, -1));

        jTextField_direccion.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 145, 240, -1));

        jTextField_telefono.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_telefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, 210, -1));

        jTextField_Name.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 210, -1));

        jTextField_email.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 75, 210, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Creado por Miguel S.A ©");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ultima modificación hecha por:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informacion del Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Eliminar cliente de base de datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));
        getContentPane().add(jLabel_wallpaper4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 606, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int option_ok = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este cliente?", "Advertencia", JOptionPane.OK_CANCEL_OPTION);

        if (option_ok == JOptionPane.OK_OPTION) {

            try {

                Connection cn_d = get_connection.connect();
                PreparedStatement pst_d = cn_d.prepareStatement("delete from clientes where nombre_cliente = '" + Tabla_Eliminar_Clientes.client_delete + "'");

                pst_d.executeUpdate();
                
                jTextField_Name.setBackground(Color.PINK);
                jTextField_direccion.setBackground(Color.PINK);
                jTextField_email.setBackground(Color.PINK);
                jTextField_telefono.setBackground(Color.PINK);
                jTextField_ultimaMody.setBackground(Color.PINK);
                
                JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente");
               
                this.dispose();
                
            } catch (SQLException e) {
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wallpaper4;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_telefono;
    private javax.swing.JTextField jTextField_ultimaMody;
    // End of variables declaration//GEN-END:variables
}
