
package windows;

import java.sql.*;
import classes.get_connection;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Gestion_de_Usuarios extends javax.swing.JFrame {

    public static String user_update = "";
    DefaultTableModel model_1 = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
        return false;
        
    }
    };
    
    
    
    public Gestion_de_Usuarios() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Gestion de Usuarios.");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        
        ImageIcon imag_3 = new ImageIcon("src/images/wallpaper2.png");

        Icon ic_1 = new ImageIcon(imag_3.getImage().getScaledInstance(jLabel_wallpaper3.getWidth(),
                jLabel_wallpaper3.getHeight(), Image.SCALE_DEFAULT));

        jLabel_wallpaper3.setIcon(ic_1);
        this.repaint();
        
        try {
            
            Connection cn_1 = get_connection.connect();
            PreparedStatement pst = cn_1.prepareStatement("select id_usuario, nombre_usuario, username, tipo_nivel, estatus from usuarios ");
            
            ResultSet rs = pst.executeQuery();
            
            jTable1 = new JTable(model_1);
            jScrollPane1.setViewportView(jTable1);
            
            model_1.addColumn("ID");
            model_1.addColumn("Nombre ");
            model_1.addColumn("Nombre de usuario");
            model_1.addColumn("Tipo de permisos");
            model_1.addColumn("Estado de plataforma");
            
            while (rs.next()){
                
                Object[] rw = new Object[5];
                
                for (int i = 0; i < 5; i++) {
                    
                    rw[i] = rs.getObject(i+1);
                    
                }
                
                model_1.addRow(rw);
                
            }
                
               
                
            
            
            
            
        } catch (SQLException e) {
        }
        
        jTable1.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseClicked(MouseEvent ev){
                
                int fila_tabla = jTable1.rowAtPoint(ev.getPoint());
                int columna_tabla = 2;
                
                if (fila_tabla > -1){
                    
                    
                    
                    user_update = (String)model_1.getValueAt(fila_tabla, columna_tabla);
                    
                    Informacion_Usuario info_user_1 = new Informacion_Usuario();
                    info_user_1.setVisible(true);
                    
                  
                    
                  
                    
                    
                    
                    
                    
                    
                    
                }
                
                
                
            }
        
        });
    }
    
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logo_icon2.png"));
        
        return retValue;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_wallpaper3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuarios Registrados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 5, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Creado por Miguel S.A ©");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 610, 190));
        getContentPane().add(jLabel_wallpaper3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         try {
            
            Connection cn_1 = get_connection.connect();
            PreparedStatement pst = cn_1.prepareStatement("select id_usuario, nombre_usuario, username, tipo_nivel, estatus from usuarios ");
            
            ResultSet rs = pst.executeQuery();
            
            model_1.setRowCount(0);
            
            jTable1 = new JTable(model_1);
            jScrollPane1.setViewportView(jTable1);
            
            
            while (rs.next()){
                
                Object[] rw = new Object[5];
                
                for (int i = 0; i < 5; i++) {
                    
                    rw[i] = rs.getObject(i+1);
                    
                }
                
                model_1.addRow(rw);
                
            }
                
               
                
            
            
            
            
        } catch (SQLException e) {
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_de_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_wallpaper3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
