/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import classes.get_connection;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;





/**
 *
 * @author pc
 */
public class Gestion_de_equipos extends javax.swing.JFrame {
    
    public static int ID_E_2;

    DefaultTableModel model_2 = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {

            return false;
        }

    };

    public Gestion_de_equipos() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Gestion de Equipos.");

        ImageIcon imag_1 = new ImageIcon("src/images/wallpaper2.png");

        Icon ic_1 = new ImageIcon(imag_1.getImage().getScaledInstance(jLabel_wallpaper4.getWidth(),
                jLabel_wallpaper4.getHeight(), Image.SCALE_DEFAULT));

        jLabel_wallpaper4.setIcon(ic_1);

        jComboBox1.removeAllItems();
        jComboBox1.addItem("Todos");
        jComboBox1.addItem("Nuevo ingreso");
        jComboBox1.addItem("En mantenimiento");
        jComboBox1.addItem("Reparado");
        jComboBox1.addItem("Entregado");

        try {

            Connection cn_1 = get_connection.connect();
            PreparedStatement pst = cn_1.prepareStatement("select id_equipo, tipo_equipo, marca, estatus from equipos");

            jTable1 = new JTable(model_2);
            jScrollPane_clientes.setViewportView(jTable1);

            model_2.addColumn("ID Equipo");
            model_2.addColumn("Tipo de equipo");
            model_2.addColumn("Marca");
            model_2.addColumn("Estatus");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                Object[] rw = new Object[4];

                for (int i = 0; i < 4; i++) {

                    rw[i] = rs.getObject(i + 1);

                }
                model_2.addRow(rw);
            }

        } catch (SQLException e) {
            System.out.println("SQL ERROR! " + e);
        }

        jTable1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent ev) {

                int fila_tabla = jTable1.rowAtPoint(ev.getPoint());
                int columna_tabla = 0;

                if (fila_tabla > -1) {

                    ID_E_2 = (int) model_2.getValueAt(fila_tabla, columna_tabla);

                    Informacion_equipos_Tecnico info_e_tec = new Informacion_equipos_Tecnico();
                    info_e_tec.setVisible(true);

                }

            }

        });

        this.repaint();

    }
    
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logo_icon2.png"));
        
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane_clientes = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_wallpaper4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Creado por Miguel S.A ©");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Equipos Registrados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 5, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_clientes.setViewportView(jTable1);

        getContentPane().add(jScrollPane_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 610, 190));
        getContentPane().add(jLabel_wallpaper4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 636, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String seleccion;
        seleccion = jComboBox1.getSelectedItem().toString();

        if (!seleccion.equals("Todos")) {

            try {

                Connection cn_2 = get_connection.connect();
                PreparedStatement pst_2 = cn_2.prepareStatement("select id_equipo, tipo_equipo, marca, estatus from equipos where estatus = '" + seleccion + "'");

                model_2.setRowCount(0);

                jTable1 = new JTable(model_2);
                jScrollPane_clientes.setViewportView(jTable1);

                ResultSet rs_2 = pst_2.executeQuery();

                while (rs_2.next()) {

                    Object[] rw = new Object[4];

                    for (int i = 0; i < 4; i++) {

                        rw[i] = rs_2.getObject(i + 1);

                    }
                    model_2.addRow(rw);

                }

            } catch (SQLException e) {
            }

        }
        
        else{
            
            try {

                Connection cn_3 = get_connection.connect();
                PreparedStatement pst_3 = cn_3.prepareStatement("select id_equipo, tipo_equipo, marca, estatus from equipos");

                model_2.setRowCount(0);

                jTable1 = new JTable(model_2);
                jScrollPane_clientes.setViewportView(jTable1);

                ResultSet rs_3 = pst_3.executeQuery();

                while (rs_3.next()) {

                    Object[] rw = new Object[4];

                    for (int i = 0; i < 4; i++) {

                        rw[i] = rs_3.getObject(i + 1);

                    }
                    model_2.addRow(rw);

                }

            } catch (SQLException e) {
            }
            
            
        
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_de_equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_wallpaper4;
    private javax.swing.JScrollPane jScrollPane_clientes;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
}
