/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import classes.get_connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static windows.Gestion_de_Usuarios.user_update;

/**
 *
 * @author pc
 */
public class Informacion_Usuario extends javax.swing.JFrame {

    int ID;
    public Informacion_Usuario() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Informacion de Usuario.");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        
    
        jComboBox_Update.removeAllItems();
        jComboBox_Update.addItem("---");
        jComboBox_Update.addItem("Administrador");
        jComboBox_Update.addItem("Asistente");
        jComboBox_Update.addItem("Tecnico");

        jComboBox_estatus.removeAllItems();
        jComboBox_estatus.addItem("---");
        jComboBox_estatus.addItem("Activo");
        jComboBox_estatus.addItem("Inactivo");

        ImageIcon imag_3 = new ImageIcon("src/images/wallpaper2.png");

        Icon ic_1 = new ImageIcon(imag_3.getImage().getScaledInstance(jLabel_wallpaper4.getWidth(),
                jLabel_wallpaper4.getHeight(), Image.SCALE_DEFAULT));

        jLabel_wallpaper4.setIcon(ic_1);
        jLabel_InfoUser.setText("Informacion del Usuario " + Gestion_de_Usuarios.user_update);
        
        try {
            
            Connection cn_3 = get_connection.connect();
            PreparedStatement pst_3 = cn_3.prepareStatement("select * from usuarios where username = '" + Gestion_de_Usuarios.user_update + "'");
            
            ResultSet rs_3 = pst_3.executeQuery();
            
            if (rs_3.next()) {
               
                ID = rs_3.getInt("id_usuario");
                
                jTextField_nameUpdate.setText(rs_3.getString("nombre_usuario"));
                jTextField_mailUpdate.setText(rs_3.getString("email"));
                jTextField_phoneUpdate1.setText(rs_3.getString("telefono"));
                jTextField_usernameUpdate.setText(rs_3.getString("username"));
                jTextField_registrationUser.setText(rs_3.getString("registrado_por"));
                
                jComboBox_Update.setSelectedItem(rs_3.getString("tipo_nivel"));
                jComboBox_estatus.setSelectedItem(rs_3.getString("estatus"));
                
                
            }
            
        } catch (SQLException e) {
        }

        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logo_icon2.png"));
        
        return retValue;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_InfoUser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_registrationUser = new javax.swing.JTextField();
        jTextField_phoneUpdate1 = new javax.swing.JTextField();
        jTextField_mailUpdate = new javax.swing.JTextField();
        jTextField_usernameUpdate = new javax.swing.JTextField();
        jTextField_nameUpdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_estatus = new javax.swing.JComboBox<>();
        jComboBox_Update = new javax.swing.JComboBox<>();
        jButton_PasswordUpdate = new javax.swing.JButton();
        jButton_InfoUpdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel_wallpaper4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                none(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_InfoUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_InfoUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_InfoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registrado por:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 215, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estatus:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 135, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 215, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTextField_registrationUser.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_registrationUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_registrationUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_registrationUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_registrationUserFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_registrationUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 240, 220, -1));

        jTextField_phoneUpdate1.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_phoneUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_phoneUpdate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_phoneUpdate1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_phoneUpdate1FocusGained(evt);
            }
        });
        getContentPane().add(jTextField_phoneUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, -1));

        jTextField_mailUpdate.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_mailUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_mailUpdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_mailUpdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_mailUpdateFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_mailUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, -1));

        jTextField_usernameUpdate.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_usernameUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_usernameUpdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_usernameUpdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameUpdateFocusGained(evt);
            }
        });
        jTextField_usernameUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_usernameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 85, 220, -1));

        jTextField_nameUpdate.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_nameUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_nameUpdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_nameUpdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nameUpdateFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_nameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, 220, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Asignar permisos de:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jComboBox_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 160, 140, -1));

        jComboBox_Update.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 305, 140, -1));

        jButton_PasswordUpdate.setBackground(new java.awt.Color(255, 255, 102));
        jButton_PasswordUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_PasswordUpdate.setText("Reiniciar Password");
        jButton_PasswordUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PasswordUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_PasswordUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 210, -1));

        jButton_InfoUpdate.setBackground(new java.awt.Color(0, 255, 204));
        jButton_InfoUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_InfoUpdate.setText("Actualizar Usuario");
        jButton_InfoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InfoUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_InfoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 210, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Creado por Miguel S.A ©");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));
        getContentPane().add(jLabel_wallpaper4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usernameUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameUpdateActionPerformed

    private void jButton_PasswordUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PasswordUpdateActionPerformed
        run_once1(reset_pas);
        
    }//GEN-LAST:event_jButton_PasswordUpdateActionPerformed

    private void jButton_InfoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InfoUpdateActionPerformed

        int permisos_int_2, estatus_int, validacion_2 = 0;
        String permisos_string_2 = "", estatus_string = "";

        permisos_int_2 = jComboBox_Update.getSelectedIndex();
        estatus_int = jComboBox_estatus.getSelectedIndex();

        String name_update = jTextField_nameUpdate.getText().trim();
        String mail_update = jTextField_mailUpdate.getText().trim();
        String phone_update = jTextField_phoneUpdate1.getText().trim();
        String username_update = jTextField_usernameUpdate.getText().trim();
        String registration_1 = jTextField_registrationUser.getText().trim();

        switch (permisos_int_2) {
            case 1:
                permisos_string_2 = "Administrador";

                break;
            case 2:
                permisos_string_2 = "Asistente";

                break;
            case 3:
                permisos_string_2 = "Tecnico";

                break;
            default:
              
                validacion_2++;
                break;
        }

        switch (estatus_int) {
            case 1:

                estatus_string = "Activo";

                break;
            case 2:

                estatus_string = "Inactivo";

                break;
            default:
               
                validacion_2++;
                break;
        }


        if (name_update.equals("")) {

            jTextField_nameUpdate.setBackground(Color.PINK);
            validacion_2++;

        }

        if (mail_update.equals("")) {

            jTextField_mailUpdate.setBackground(Color.PINK);
            validacion_2++;

        }

        if (phone_update.equals("")) {

            jTextField_phoneUpdate1.setBackground(Color.PINK);
            validacion_2++;

        }

        if (username_update.equals("")) {

            jTextField_usernameUpdate.setBackground(Color.PINK);
            validacion_2++;

        }

        if (registration_1.equals("")) {

            jTextField_registrationUser.setBackground(Color.PINK);
            validacion_2++;

        }

        try {
            Connection cn_1 = get_connection.connect();
            PreparedStatement ps_1 = cn_1.prepareStatement(" select username from usuarios where username = '" + username_update + "'");

            ResultSet rs = ps_1.executeQuery();

            if (rs.next()) {

                jTextField_usernameUpdate.setBackground(Color.PINK);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                jTextField_usernameUpdate.setText("");
                cn_1.close();

            } else {

                cn_1.close();

                if (validacion_2 == 0) {

                    try {

                        Connection cn_2 = get_connection.connect();
                        PreparedStatement pst_2 = cn_2.prepareStatement("update usuarios set nombre_usuario = ?, email = ?, telefono = ?, username = ?, tipo_nivel = ?, estatus = ?, registrado_por = ? where username = '" + Gestion_de_Usuarios.user_update + "'");

                        pst_2.setString(1, name_update);
                        pst_2.setString(2, mail_update);
                        pst_2.setString(3, phone_update);
                        pst_2.setString(4, username_update);
                        pst_2.setString(5, permisos_string_2);
                        pst_2.setString(6, estatus_string);
                        pst_2.setString(7, registration_1);
                        pst_2.executeUpdate();

                        cn_2.close();
                        
                        this.dispose();
                        
                        
                        jTextField_nameUpdate.setBackground(new Color(51, 255, 51));
                        jTextField_mailUpdate.setBackground(new Color(51, 255, 51));
                        jTextField_phoneUpdate1.setBackground(new Color(51, 255, 51));
                        jTextField_usernameUpdate.setBackground(new Color(51, 255, 51));
                        jTextField_registrationUser.setBackground(new Color(51, 255, 51));
                        
                        JOptionPane.showMessageDialog(null, "Datos actualizados correctamente.");
                        
                        jTextField_nameUpdate.setBackground(new Color(153, 204, 255));
                        jTextField_mailUpdate.setBackground(new Color(153, 204, 255));
                        jTextField_phoneUpdate1.setBackground(new Color(153, 204, 255));
                        jTextField_usernameUpdate.setBackground(new Color(153, 204, 255));
                        jTextField_registrationUser.setBackground(new Color(204, 204, 204));

                    } catch (HeadlessException | SQLException e) {
                        System.out.println("SQL Error! " + e);
                    }

                }
                
                else{
                    
                    JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }

            }
        } catch (SQLException e) {
        }


    }//GEN-LAST:event_jButton_InfoUpdateActionPerformed

    private void none(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_none
   
    }//GEN-LAST:event_none

    private void jTextField_nameUpdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameUpdateFocusGained
        jTextField_nameUpdate.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_nameUpdateFocusGained

    private void jTextField_mailUpdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_mailUpdateFocusGained
        jTextField_mailUpdate.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_mailUpdateFocusGained

    private void jTextField_phoneUpdate1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_phoneUpdate1FocusGained
        jTextField_phoneUpdate1.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_phoneUpdate1FocusGained

    private void jTextField_usernameUpdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameUpdateFocusGained
        jTextField_usernameUpdate.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_usernameUpdateFocusGained

    private void jTextField_registrationUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_registrationUserFocusGained
        jTextField_registrationUser.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_jTextField_registrationUserFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_InfoUpdate;
    private javax.swing.JButton jButton_PasswordUpdate;
    private javax.swing.JComboBox<String> jComboBox_Update;
    private javax.swing.JComboBox<String> jComboBox_estatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_InfoUser;
    private javax.swing.JLabel jLabel_wallpaper4;
    private javax.swing.JTextField jTextField_mailUpdate;
    private javax.swing.JTextField jTextField_nameUpdate;
    private javax.swing.JTextField jTextField_phoneUpdate1;
    private javax.swing.JTextField jTextField_registrationUser;
    private javax.swing.JTextField jTextField_usernameUpdate;
    // End of variables declaration//GEN-END:variables
 
    Reiniciar_Password reset_pas = new Reiniciar_Password();
    
    public void run_once1(JFrame reference_1){
    
        reset_pas.setVisible(false);
        reset_pas = (Reiniciar_Password) reference_1;
        reset_pas.setVisible(true);
        
    }
     
}
