/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import classes.get_connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author pc
 */
public class Registro_de_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Registro_de_Producto
     */
    public Registro_de_Producto() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registro de computador nuevo para " + Gestion_de_Clientes.client);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        jComboBox_tipoCompu.removeAllItems();
        jComboBox_tipoCompu.addItem("---");
        jComboBox_tipoCompu.addItem("Laptop");
        jComboBox_tipoCompu.addItem("Escritorio");
        jComboBox_tipoCompu.addItem("Todo en uno");
        
        jComboBox_marca.removeAllItems();
        jComboBox_marca.addItem("---");
        jComboBox_marca.addItem("Acer");
        jComboBox_marca.addItem("Lenovo");
        jComboBox_marca.addItem("Hp");
        jComboBox_marca.addItem("Dell");
        jComboBox_marca.addItem("Apple");
        
        try {
            
            Connection cn_1 = get_connection.connect();
            PreparedStatement pst = cn_1.prepareStatement("select nombre_cliente from clientes where nombre_cliente = '" + Gestion_de_Clientes.client + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                
                jTextField_nombreCliente.setText(rs.getString("nombre_cliente"));
                
            }
            
            
            
        } catch (SQLException e) {
        }
        
        
        ImageIcon imag_1 = new ImageIcon("src/images/wallpaper2.png");

        Icon ic_1 = new ImageIcon(imag_1.getImage().getScaledInstance(jLabel_wallpaper4.getWidth(),
                jLabel_wallpaper4.getHeight(), Image.SCALE_DEFAULT));

        jLabel_wallpaper4.setIcon(ic_1);
        
        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logo_icon2.png"));
        
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_numSerie = new javax.swing.JTextField();
        jTextField_Modelo = new javax.swing.JTextField();
        jTextField_nombreCliente = new javax.swing.JTextField();
        jComboBox_marca = new javax.swing.JComboBox<>();
        jComboBox_tipoCompu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel_wallpaper4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Daños y observaciones:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de serie:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modelo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de computadores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jTextField_numSerie.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_numSerie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_numSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_numSerieFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_numSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 365, 240, -1));

        jTextField_Modelo.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_Modelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_Modelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ModeloFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 295, 240, -1));

        jTextField_nombreCliente.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_nombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_nombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nombreClienteFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 85, 240, -1));

        jComboBox_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, 140, -1));

        jComboBox_tipoCompu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_tipoCompu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 155, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de computador:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Creado por Miguel S.A ©");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 425, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Registrar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 390, 240));
        getContentPane().add(jLabel_wallpaper4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 765, 465));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String modelo = "", num_serie = "", tipo_comp_string = "", marca_string = "", 
                observ = "", estatus, dia, mes, annio;
        int tipo_comp_int = 0, marca_int = 0, validacion = 0;
        
        Calendar calendario = Calendar.getInstance();
        
        dia = Integer.toString(calendario.get(Calendar.DATE));
        mes = Integer.toString(calendario.get(Calendar.MONTH ) + 1);
        annio = Integer.toString(calendario.get(Calendar.YEAR));
        
        tipo_comp_int = jComboBox_tipoCompu.getSelectedIndex();
        marca_int = jComboBox_marca.getSelectedIndex();
        observ = jTextPane1.getText();
        estatus = "Nuevo ingreso";
        
        modelo = jTextField_Modelo.getText().trim();
        num_serie = jTextField_numSerie.getText().trim();
        
        switch (tipo_comp_int) {
            case 1:
              
                tipo_comp_string = "Laptop";
                
                break;
                
            case 2:
                              
                 tipo_comp_string = "Escritorio";
                
                break;
                
            case 3:
                              
                 tipo_comp_string = "Todo en uno";
                
                break;       
            default:
                
                validacion++;
                
                break;
        }
        
        switch (marca_int) {
            case 1:
                
                marca_string = "Acer";
                
                break;
                
            case 2:
                
                marca_string = "Lenovo";
                
                break;
                
            case 3:
                
                marca_string = "Hp";
                
                break;
                
            case 4:
                
                marca_string = "Dell";
                
                break;        
            case 5:
                
                marca_string = "Apple";
                
                break;        
            default:
                
                validacion++;
                
                break;
        }
        
        if (modelo.equals("") & num_serie.equals("") & observ.equals("")) {
            
            validacion++;
            jTextField_Modelo.setBackground(Color.PINK);
            jTextField_numSerie.setBackground(Color.PINK);
            
        }
        
        if (modelo.equals("")){
            
            jTextField_Modelo.setBackground(Color.PINK);
            validacion++;
        }
        
        if (num_serie.equals("")) {
            
            jTextField_numSerie.setBackground(Color.PINK);
            validacion++;
            
        }
        
        if (observ.equals("")) {
            
            
            validacion++;
            
        }
        
        
        
        try {
            if (validacion != 0) {
                
                JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos", "Advertencia", JOptionPane.ERROR_MESSAGE);
                
            }
            
            else {
                
                Connection cn_2 = get_connection.connect();
                PreparedStatement pst_2 = cn_2.prepareStatement("insert into equipos values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                
                
                pst_2.setInt(1, 0);
                pst_2.setInt(2, Info_Clientes.ID);
                pst_2.setString(3, tipo_comp_string);
                pst_2.setString(4, marca_string);
                pst_2.setString(5, modelo);
                pst_2.setString(6, num_serie);
                pst_2.setString(7, dia);
                pst_2.setString(8, mes);
                pst_2.setString(9, annio);
                pst_2.setString(10, observ);
                pst_2.setString(11, estatus);
                pst_2.setString(12, Login.user);
                pst_2.setString(13, "");
                pst_2.setString(14, "");
                
                
                pst_2.executeUpdate();
                cn_2.close();
                
                jTextField_Modelo.setBackground(new Color(51, 255, 51));
                jTextField_numSerie.setBackground(new Color(51, 255, 51));
                
                JOptionPane.showMessageDialog(null, "Registro de computador exitoso.");
                
                this.dispose();
            }
            
            
        } catch (HeadlessException | SQLException e) {
            
            System.out.println("SQL ERROR! " + e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_nombreClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nombreClienteFocusGained
        
        jTextField_nombreCliente.setBackground(new Color(255,204,153));
        
    }//GEN-LAST:event_jTextField_nombreClienteFocusGained

    private void jTextField_ModeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ModeloFocusGained
        
        jTextField_Modelo.setBackground(new Color(255,204,153));
        
    }//GEN-LAST:event_jTextField_ModeloFocusGained

    private void jTextField_numSerieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_numSerieFocusGained
        
        jTextField_numSerie.setBackground(new Color(255,204,153));
        
    }//GEN-LAST:event_jTextField_numSerieFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_de_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_marca;
    private javax.swing.JComboBox<String> jComboBox_tipoCompu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wallpaper4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_nombreCliente;
    private javax.swing.JTextField jTextField_numSerie;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
