/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import classes.get_connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Registro_de_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Registro_de_Usuario
     */
    public Registro_de_Usuario() {
        initComponents();
        setSize(610, 420);
        setTitle("Registro de Usuarios.");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        jComboBox1.removeAllItems();
        jComboBox1.addItem("---");
        jComboBox1.addItem("Administrador");
        jComboBox1.addItem("Asistente");
        jComboBox1.addItem("Tecnico");

        ImageIcon imag_3 = new ImageIcon("src/images/wallpaper2.png");

        Icon ic_1 = new ImageIcon(imag_3.getImage().getScaledInstance(jLabel_wallpaper3.getWidth(),
                jLabel_wallpaper3.getHeight(), Image.SCALE_DEFAULT));

        jLabel_wallpaper3.setIcon(ic_1);
        this.repaint();

    }
     
    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logo_icon2.png"));
        return retValue;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_username1 = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_phone = new javax.swing.JLabel();
        jLabel_mail = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField_pass = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jTextField_phone = new javax.swing.JTextField();
        jTextField_nombre1 = new javax.swing.JTextField();
        jTextField_mail = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel_wallpaper3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(610, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Creado por Miguel S.A ©");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Asignar permisos de:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel_username1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_username1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_username1.setText("Password:");
        getContentPane().add(jLabel_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jLabel_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_username.setText("Nombre de usuario:");
        getContentPane().add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel_phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_phone.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_phone.setText("Telefono:");
        getContentPane().add(jLabel_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel_mail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_mail.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mail.setText("email:");
        getContentPane().add(jLabel_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setText("Nombre:");
        getContentPane().add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 120, 100));

        jTextField_pass.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_pass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_passFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 175, 190, -1));

        jTextField_username.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 105, 190, -1));

        jTextField_phone.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_phone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_phoneFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 245, 190, -1));

        jTextField_nombre1.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_nombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_nombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_nombre1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_nombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nombre1FocusGained(evt);
            }
        });
        getContentPane().add(jTextField_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, 190, -1));

        jTextField_mail.setBackground(new java.awt.Color(255, 204, 153));
        jTextField_mail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_mail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_mailFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, 190, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 305, 140, -1));

        jLabel_wallpaper3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel_wallpaper3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 620, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int permisos_int, validacion = 0;
        String permisos_string = "", name_1, mail_1, p_number, username, password;

        name_1 = jTextField_nombre1.getText().trim();
        mail_1 = jTextField_mail.getText().trim();
        p_number = jTextField_phone.getText().trim();
        username = jTextField_username.getText().trim();
        password = jTextField_pass.getText().trim();

        permisos_int = jComboBox1.getSelectedIndex();

       

        if (name_1.equals("")) {

            jTextField_nombre1.setBackground(Color.PINK);
            validacion++;

        }

        if (mail_1.equals("")) {

            jTextField_mail.setBackground(Color.PINK);
            validacion++;

        }

        if (p_number.equals("")) {

            jTextField_phone.setBackground(Color.PINK);
            validacion++;

        }

        if (username.equals("")) {

            jTextField_username.setBackground(Color.PINK);
            validacion++;

        }

        if (password.equals("")) {

            jTextField_pass.setBackground(Color.PINK);
            validacion++;

        }

        switch (permisos_int) {
            case 1:
                permisos_string = "Administrador";
                break;
            case 2:
                permisos_string = "Asistente";
                break;
            case 3:
                permisos_string = "Tecnico";
                break;
            default:
                
                validacion++;
                break;
        }

        try {

            Connection cn_1 = get_connection.connect();
            PreparedStatement ps_1 = cn_1.prepareStatement(" select username from usuarios where username = '" + username + "'");

            ResultSet rs = ps_1.executeQuery();

            if (rs.next()) {

                jTextField_username.setBackground(Color.PINK);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                jTextField_username.setText("");
                cn_1.close();

            } else {

                cn_1.close();

                if (validacion == 0) {
                    try {
                        Connection cn_2 = get_connection.connect();
                        PreparedStatement ps_2 = cn_2.prepareStatement(
                                "insert into usuarios values (?,?,?,?,?,?,?,?,?)");

                        ps_2.setInt(1, 0);
                        ps_2.setString(2, jTextField_nombre1.getText());
                        ps_2.setString(3, jTextField_mail.getText());
                        ps_2.setString(4, jTextField_phone.getText());
                        ps_2.setString(5, jTextField_username.getText());
                        ps_2.setString(6, jTextField_pass.getText());
                        ps_2.setString(7, permisos_string);
                        ps_2.setString(8, "Activo");
                        ps_2.setString(9, Login.user);

                        ps_2.executeUpdate();
                        cn_2.close();
                        
                        

                        jTextField_nombre1.setBackground(new Color(51, 255, 51));
                        jTextField_mail.setBackground(new Color(51, 255, 51));
                        jTextField_phone.setBackground(new Color(51, 255, 51));
                        jTextField_username.setBackground(new Color(51, 255, 51));
                        jTextField_pass.setBackground(new Color(51, 255, 51));

                        JOptionPane.showMessageDialog(null, "Registro de usuario existoso.");

                        this.dispose();
                        
                        jTextField_nombre1.setBackground(new Color(153, 204, 255));
                        jTextField_mail.setBackground(new Color(153, 204, 255));
                        jTextField_phone.setBackground(new Color(153, 204, 255));
                        jTextField_username.setBackground(new Color(153, 204, 255));
                        jTextField_pass.setBackground(new Color(153, 204, 255));

                    } catch (HeadlessException | SQLException e) {
                        System.out.println("Error?" + e);
                    }

                }
                
                else{
                    
                    JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos", "Advertencia", JOptionPane.ERROR_MESSAGE);
                    
                }

            }
        } catch (HeadlessException | SQLException e) {

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_nombre1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nombre1FocusGained
        jTextField_nombre1.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_nombre1FocusGained

    private void jTextField_mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_mailFocusGained
        jTextField_mail.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_mailFocusGained

    private void jTextField_phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_phoneFocusGained
        jTextField_phone.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_phoneFocusGained

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        jTextField_username.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_passFocusGained
        jTextField_pass.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jTextField_passFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_de_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_de_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_mail;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_phone;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JLabel jLabel_username1;
    private javax.swing.JLabel jLabel_wallpaper3;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_nombre1;
    private javax.swing.JTextField jTextField_pass;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables

    public void Clean_1(){
        
        jTextField_mail.setText("");
        jTextField_nombre1.setText("");
        jTextField_phone.setText("");
        jTextField_username.setText("");
        jTextField_pass.setText("");
        
        
    }
    
    
}
