/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import classes.get_connection;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Reiniciar_Password extends javax.swing.JFrame {

    /**
     * Creates new form Reiniciar_Password
     */
    public Reiniciar_Password() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cambio de Password.");
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       ;
        
        ImageIcon imag_4 = new ImageIcon("src/images/wallpaper2.png");
        
        Icon ic_4 = new ImageIcon(imag_4.getImage().getScaledInstance(jLabel_wallpaper4.getWidth(),
                jLabel_wallpaper4.getHeight(), Image.SCALE_DEFAULT));
        
        jLabel_wallpaper4.setIcon(ic_4);
        
        this.repaint();
        
        
    }
    
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logo_icon2.png"));
        
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_confirmation = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPassword_confirmation = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel_wallpaper4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_confirmation.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_confirmation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_confirmation.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_confirmation.setText("Confirmar password:");
        getContentPane().add(jLabel_confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cambio de Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Reiniciar Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jPassword_confirmation.setBackground(new java.awt.Color(255, 204, 153));
        jPassword_confirmation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPassword_confirmation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPassword_confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, 320, -1));

        jPasswordField1.setBackground(new java.awt.Color(255, 204, 153));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 95, 320, -1));
        getContentPane().add(jLabel_wallpaper4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String pass_1, conf_pass;
        
        pass_1 = jPasswordField1.getText().trim();
        conf_pass = jPassword_confirmation.getText().trim();
        
        try {
            
            
            Connection cn_1 = get_connection.connect();
            PreparedStatement pst = cn_1.prepareStatement("update usuarios set password = ? where username = '" + Gestion_de_Usuarios.user_update + "'");
            
            
            if (pass_1.equals(conf_pass)) {
                
               pst.setString(1, conf_pass);
               pst.executeUpdate();
               
               cn_1.close();
               JOptionPane.showMessageDialog(null, "Nueva contraseña asignada");
                
            } else {
                
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden, trate nuevamente");
            }
    
            
        } catch (SQLException e) {
            System.out.println("Database Error! " + e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reiniciar_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reiniciar_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reiniciar_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reiniciar_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reiniciar_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_confirmation;
    private javax.swing.JLabel jLabel_wallpaper4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPassword_confirmation;
    // End of variables declaration//GEN-END:variables
}
